<?xml version="1.0"?>
<package format="2">
  <name>stier_slam_bringup</name>
  <version>0.1.0</version>
  <description>Launch and configuration package for Stier RTAB-Map SLAM.</description>
  <maintainer email="stier@example.com">Stier</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>stier_slam_core</depend>
  <depend>robot_localization</depend>
  <depend>map_server</depend>
  <depend>rtabmap_launch</depend>
  <depend>rtabmap_slam</depend>
  <depend>rosbag</depend>
  <depend>rviz</depend>
  <exec_depend>stier_slam_test_support</exec_depend>
  <test_depend>rostest</test_depend>
  <test_depend>diagnostic_msgs</test_depend>
  <test_depend>nav_msgs</test_depend>
  <test_depend>rosgraph</test_depend>
  <test_depend>rosnode</test_depend>
  <test_depend>rosgraph_msgs</test_depend>
  <test_depend>rospy</test_depend>
  <test_depend>sensor_msgs</test_depend>
  <test_depend>tf2_ros</test_depend>
  <test_depend>tf2_msgs</test_depend>
</package>
